#!/usr/bin/lua

print("Content-Type: text/html; charset=utf-8")
print("Cache-Control: no-cache, no-store, must-revalidate")
print("Pragma: no-cache")
print("Expires: 0")
print("")
print("<!DOCTYPE html>")
print("<html lang='en'>")
print("<head><meta charset='utf-8'><title>Reboot Webserver</title></head>")
print("<body style='background-color: black;color:white'>")
print("<h1>Reboot Router in Progress<h2>")
print("<p>")
print(os.date("%c"))
print( "</p>")
print("<progress></progress>")
print("<p>Click this <a href="/ping">link</a> in 30-60 seconds</p>")
print("</body></html>")
os.execute("reboot")